### PR TITLE
Re-remove kotlin-reflect dependency

### LINKED ISSUE #1179: Master is broken
Running `./gradlew` on `master` fails with the following exception:

```
Script compilation error:

  Line 211:             kotlinTest("org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion")
                                                               ^ Unresolved reference: kotlinVersion

```

I suspect this is caused by a bad merge.

The fix is to change line `211` to: `kotlinTest(kotlin("reflect"))`

### PR DESCRIPTION
**Pull request by 3flex**
Something funky happened when #1151 was merged - this fixes the build which is currently failing.

Fixes #1179 closes #1180

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Can this be merged so that work on `master can continue?
