### ISSUE TITLE
UselessCallOnNotNull doesn't report

### ISSUE THREAD

**Issue by CuiLam** [arturbosch/detekt#2037]
I wrote `val testList = listOf("string").orEmpty()` in my code, but detekt can not find it.

**Comment by 3flex** [comment]
Can you please take a look at my comment on #2036 and see if it sinilarly describes your issue?

**Comment by CuiLam** [comment]
yes, it 's sinilarly

**Comment by CuiLam** [comment]
so now what can I do

**Comment by 3flex** [comment]
We need to write docs so users know how to run detekt so all rules run as expected.

We're aware, just need to find the time to work on it.

If using Gradle try running `detektMain` task.

**Comment by CuiLam** [comment]
When i running detektMain tash, it report 

Script compilation errors:

  Line 23:     plugins {
               ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                   public inline operator fun <T : Any, C : NamedDomainObjectContainer<TypeVariable(T)>> TypeVariable(C).invoke(configuration: NamedDomainObjectContainerScope<TypeVariable(T)>.() -> Unit): TypeVariable(C) defined in org.gradle.kotlin.dsl
                   public operator fun <T> Closure<TypeVariable(T)>.invoke(): TypeVariable(T) defined in org.gradle.kotlin.dsl
                   public operator fun <T> Closure<TypeVariable(T)>.invoke(x: Any?): TypeVariable(T) defined in org.gradle.kotlin.dsl
                   public operator fun <T> Closure<TypeVariable(T)>.invoke(vararg xs: Any?): TypeVariable(T) defined in org.gradle.kotlin.dsl
                   public operator fun <V> Callable<TypeVariable(V)>.invoke(): TypeVariable(V) defined in org.gradle.kotlin.dsl
                   public inline operator fun <reified T> Action<in TypeVariable(T)>.invoke(target: TypeVariable(T)): Unit defined in org.gradle.kotlin.dsl
                   public operator fun <T> NamedDomainObjectProvider<TypeVariable(T)>.invoke(action: TypeVariable(T).() -> Unit): Unit defined in org.gradle.kotlin.dsl
                   @Incubating public operator fun ArtifactHandler.invoke(configuration: ArtifactHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
                   @Incubating public operator fun DependencyConstraintHandler.invoke(configuration: DependencyConstraintHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
                   public inline operator fun <T> ExtraPropertiesExtension.invoke(initialValueProvider: () -> TypeVariable(T)): InitialValueExtraPropertyDelegateProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                   public operator fun <T> ExtraPropertiesExtension.invoke(initialValue: TypeVariable(T)): InitialValueExtraPropertyDelegateProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                   public operator fun <T> Spec<TypeVariable(T)>.invoke(arg: TypeVariable(T)): Boolean defined in org.gradle.kotlin.dsl
                   public inline operator fun TaskContainer.invoke(configuration: TaskContainerScope.() -> Unit): TaskContainer defined in org.gradle.kotlin.dsl

  Line 24:         id("com.jfrog.artifactory") version artifactoryVersion
                   ^ Unresolved reference: id

  Line 25:         id("com.jfrog.bintray") version bintrayVersion
                   ^ Unresolved reference: id

  Line 26:         id("com.gradle.build-scan") version buildScanVersion
                   ^ Unresolved reference: id

  Line 27:         id("org.jetbrains.dokka") version dokkaVersion
                   ^ Unresolved reference: id

  Line 28:         id("com.github.ben-manes.versions") version gradleVersionsPluginVersion
                   ^ Unresolved reference: id

  Line 29:         kotlin("jvm") version kotlinVersion
                   ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                       public fun DependencyHandler.kotlin(module: String, version: String? = ...): Any defined in org.gradle.kotlin.dsl
                       public fun PluginDependenciesSpec.kotlin(module: String): PluginDependencySpec defined in org.gradle.kotlin.dsl

  Line 30:         id("com.github.johnrengelman.shadow") version shadowVersion
                   ^ Unresolved reference: id

  Line 31:         id("org.sonarqube") version sonarQubeVersion
                   ^ Unresolved reference: id

9 errors

**Comment by dive5617** [comment]
so all rules work well in v1.1.1. Issues for example #2043 are caused by users don't know how to run it even for android project. Is that right? @3flex

**Comment by 3flex** [comment]
@CuiLam those errors are Gradle script compilation errors which don't look related to detekt itself, are you using Gradle to build your project or just trying to run the detekt Gradle task?

@dive5617 basically yes. We need to make a couple more improvements then write docs.

**Comment by CuiLam** [comment]
I can't run detekyMain in my android project, so how can I do that

**Comment by schalkms** [comment]
#2259 shows how to run `detektMain` on Android.
