### PR TITLE
Fix build failing to compile on master

### LINKED ISSUE #1179: Master is broken
Running `./gradlew` on `master` fails with the following exception:

```
Script compilation error:

  Line 211:             kotlinTest("org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion")
                                                               ^ Unresolved reference: kotlinVersion

```

I suspect this is caused by a bad merge.

The fix is to change line `211` to: `kotlinTest(kotlin("reflect"))`

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #1179

### CODE REVIEW

**Comment by pavlospt** [comment]
There is a PR removing this dependency #1177 . I am not sure it should be added again :P

**Comment by JLLeitschuh** [comment]
Probably correct, I was just trying to make it compile.
