### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by JLLeitschuh** [arturbosch/detekt#1179]
Running `./gradlew` on `master` fails with the following exception:

```
Script compilation error:

  Line 211:             kotlinTest("org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion")
                                                               ^ Unresolved reference: kotlinVersion

```

I suspect this is caused by a bad merge.

The fix is to change line `211` to: `kotlinTest(kotlin("reflect"))`

**Comment by Mauin** [comment]
Master is green again.
